const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  const [deployer] = await hre.ethers.getSigners();
  const network = hre.network.name;
  const balance = await hre.ethers.provider.getBalance(deployer.address);

  console.log(`\n--- LitGive deployment ---`);
  console.log(`Network    : ${network}`);
  console.log(`Deployer   : ${deployer.address}`);
  console.log(`Balance    : ${hre.ethers.formatEther(balance)} zkLTC`);

  if (balance === 0n) {
    console.warn("\n⚠️  Deployer balance is 0. Get testnet zkLTC from https://testnet.litvm.com\n");
  }

  const feeRecipient = deployer.address; // can be changed later via setFeeRecipient
  const platformFeeBps = 200; // 2%

  console.log(`\nDeploying DonationPlatform...`);
  console.log(`  feeRecipient    : ${feeRecipient}`);
  console.log(`  platformFeeBps  : ${platformFeeBps} (${platformFeeBps / 100}%)`);

  const F = await hre.ethers.getContractFactory("DonationPlatform");
  const c = await F.deploy(feeRecipient, platformFeeBps);
  await c.waitForDeployment();

  const address = await c.getAddress();
  const txHash = c.deploymentTransaction()?.hash;

  console.log(`\n✅ Deployed at: ${address}`);
  console.log(`   tx: ${txHash}`);

  // Persist deployment info
  const out = {
    network,
    chainId: Number((await hre.ethers.provider.getNetwork()).chainId),
    address,
    deployer: deployer.address,
    feeRecipient,
    platformFeeBps,
    txHash,
    deployedAt: new Date().toISOString(),
  };
  const file = path.join(__dirname, "..", "deployments.json");
  fs.writeFileSync(file, JSON.stringify(out, null, 2));
  console.log(`   saved to ${file}`);

  // Helpful ABI export for the frontend
  const artifact = await hre.artifacts.readArtifact("DonationPlatform");
  const webDir = path.join(__dirname, "..", "..", "web", "src", "lib");
  if (!fs.existsSync(webDir)) fs.mkdirSync(webDir, { recursive: true });
  fs.writeFileSync(
    path.join(webDir, "abi.ts"),
    `// Auto-generated by deploy script. Do not edit.\nexport const DONATION_PLATFORM_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`
  );
  fs.writeFileSync(
    path.join(webDir, "deployment.ts"),
    `// Auto-generated by deploy script. Do not edit.\nexport const DEPLOYMENT = ${JSON.stringify(out, null, 2)} as const;\n`
  );
  console.log(`   exported ABI + deployment to web/src/lib/`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
