// Auto-generated by deploy script. Do not edit.
export const DEPLOYMENT = {
  "network": "litvmTestnet",
  "chainId": 4441,
  "address": "0x1Da9FB28c6F3B43f4d4487e833873Cf2856b809A",
  "deployer": "0xF0071AFE9ca99eB21cDDAb933837e6E280BDCB12",
  "feeRecipient": "0xF0071AFE9ca99eB21cDDAb933837e6E280BDCB12",
  "platformFeeBps": 200,
  "txHash": "0x88fdb071500d5c006a6c77a77bb448e85516813de57860b9b0abad865f59de14",
  "deployedAt": "2026-05-20T22:41:08.223Z"
} as const;
